CommunityCounts/Controllers/AnalIntroController.cs
using System.Web.Mvc;

namespace CommunityCounts.Controllers
{
   
    public class AnalIntroController : Controller
    {
        // GET: AnalIntro
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult Bespoke()
        {
            return View();
        }
        public ActionResult PivotChart()
        {
            return View();
        }
        public ActionResult DDIntro()
        {
            return View();
        }
        public ActionResult vClient()
        {
            return View();
        }
        public ActionResult vClientActivity()
        {
            return View();
        }
        public ActionResult vClientAttendance()
        {
            return View();
        }
        public ActionResult vClientNeeds()
        {
            return View();
        }
        public ActionResult vClientCasework()
        {
            return View();
        }
        public ActionResult vBookings()
        {
            return View();
        }
        public ActionResult vJourneys()
        {
            return View();
        }
        public ActionResult vAttendance()
        {
            return View();
        }
        public ActionResult vcomment()
        {
            return View();
        }
        public ActionResult vQCSR()
        {
            return View();
        }
        public ActionResult vSurveys()
        {
            return View();
        }
        public ActionResult vSurveyResultsNum()
        {
            return View();
        }
        public ActionResult vSurveyResultsTxt()
        {
            return View();
        }
    }
}

CommunityCounts/Controllers/HomeController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using CommunityCounts.Models.Master;
using CommunityCounts.Global_Methods;

namespace CommunityCounts.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            @ViewBag.userHasNews = false;
            if (Request.IsAuthenticated)
            {
                // already logged in, check for user news
                ccMaster db = new ccMaster(null);
                @ViewBag.userHasNews = CS.userHasNews(db);
                ViewBag.RegYearDate = CS.getRegYear(db,true);
                ViewBag.RegYear = CS.getRegYear(db, false);            }
           
            return View();
        }
        public ActionResult ReadMore()
        {
            @ViewBag.userHasNews = false;
            if (Request.IsAuthenticated)
            {
                // already logged in, check for user news
                ccMaster db = new ccMaster(null);
                @ViewBag.userHasNews = CS.userHasNews(db);
            }
            return View();
        }
        public ActionResult Dismiss ()
        {
            // get users logon id and set users table to stop displaying new messages
            var userName = User.Identity.Name;
            ccMaster db = new ccMaster(null);
            var us = db.users.Where(u => u.Email == userName);
            bool nameIsPresent = us.Any();
            if (nameIsPresent)
            {
                var rec = us.First();
                rec.readNews = true;
                db.Entry(rec).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult About()
        {
            ViewBag.Message = "Community Counts is developed by Next Step Forward.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Community Counts is developed by Next Step Forward.";

            return View();
        }
        [Authorize]
        public ActionResult N01P01A()
        {
            return View();
        }
        [Authorize]
        public ActionResult N01P01B()
        {
            return View();
        }
        [Authorize]
        public ActionResult ChgYear()
        {
            ccMaster db = new ccMaster(null);
            ViewBag.idRegYear = new SelectList(db.regyears,"idRegYear","RegYear1",CS.getRegYearId(db));
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult ChgYear([Bind(Include = "idRegYear")]regyear r)
        {
            ccMaster db = new ccMaster(null);
            var y = db.users.Where(u => u.Email == User.Identity.Name).First();
            y.idRegYear = r.idRegYear; // update the chosen registration year
            db.Entry(y).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CommunityCounts/Views/AnalIntro/DDIntro.cshtml
@{
    ViewBag.Title = "Analysis - The Data Dictionary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Analysis - Introduction to the Data Dictionary</h2>
<p>
    @Html.ActionLink("Back to Main Screen", "Index", "Home", null, htmlAttributes: new { @class = "btn btn-primary btn-xs" })
</p>
<div class="panel panel-default">
    <div class="panel-default">
        The <strong>Data Dictionary</strong> is how all data within Community Counts is <em>stored</em> and <em>accessed</em>
        <p>This Dictionary consists are a group of <em>related</em> data items in the following sets:
        <ol>
            <li>@Html.ActionLink("vClient","vClient","AnalIntro")<br />
                Client-related data, including all geographical-related data. Related to this are these extended data-items:
                <ol>
                    <li>
                        @Html.ActionLink("vClientActivity", "vClientActivity", "AnalIntro")<br />
                        All enrolled Activity information for a Client (and all client information). This includes Journey Category.
                    </li>
                    <li>
                        @Html.ActionLink("vClientAttendance", "vClientAttendance", "AnalIntro")<br />
                        All attendance information for a Client (and all client information).
                    </li>
                    <li>
                        @Html.ActionLink("vClientCasework", "vClientCasework", "AnalIntro")<br />
                        All attendance information for a Client (and all client information).
                    </li>
                    <li>
                        @Html.ActionLink("vClientNeeds", "vClientNeeds", "AnalIntro")<br />
                        All attendance information for a Client (and all client information).
                    </li>
                </ol>
            </li>
            <li>
                @Html.ActionLink("vBookings", "vBookings", "AnalIntro")<br />
                All bookings data. For all of the generated schedules.
            </li>
            <li>
                @Html.ActionLink("vAttendance", "vAttendance", "AnalIntro")<br />
                All Attendance data (but no Client-related information)
            </li>
            <li>
                @Html.ActionLink("vJourneys", "vJourneys", "AnalIntro")<br />
                The Parent and child Activity in any Journey.
            </li>
            <li>
                @Html.ActionLink("vcomment", "vcomment", "AnalIntro")<br />
                All Quick Contact comments.
            </li>
            <li>
                @Html.ActionLink("vQCSR", "vQCSR", "AnalIntro")<br />
                All Quick Contact and Signpost/Referral data items.
            </li>
            <li>
                @Html.ActionLink("vSurveys", "vSurveys", "AnalIntro")<br />
                All Survey definitions. Related to this are the extended data-items:
                <ol>
                    <li>
                        @Html.ActionLink("vSurveyResultsNum", "vSurveyResultsNum", "AnalIntro")<br />
                        All <em>numeric</em> results for all surveys together will related client information
                    </li>
                    <li>
                        @Html.ActionLink("vSurveyResultsTxt", "vSurveyResultsTxt", "AnalIntro")<br />
                        All <em>textural</em> results for all surveys together will related client information
                    </li>
                </ol>
            </li>
            </ol>
        </p>
    </div>
</div>

CommunityCounts/Views/AnalIntro/vAttendance.cshtml
@{
    ViewBag.Title = "Analysis - vAttendance";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Analysis - The Data Dictionary for vAttendance</h2>
<p>
    @Html.ActionLink("Back to Data Dictionary", "DDIntro", "AnalIntro", null, htmlAttributes: new { @class = "btn btn-primary btn-xs" })
</p>
<div class="alert alert-dismissible alert-warning">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Important!</h4>
    <p>There is one vAttendnace record for each session and for each Activity. As most Activities have multiple sessions (e..g. Weekly), there are multiple vBookings records for each Activity. This dataset contains no client related information. Use 
        @Html.ActionLink("vClientAttendance", "vClientAttendance", "AnalIntro", null, htmlAttributes: new { @class = "btn btn-primary btn-xs" }) for Client and Attendance information
       </p>
</div>
<table class="table table-bordered table-hover">
    <tr>
        <th>Data Dictionary item</th>
        <th>Brief description</th>
    </tr>
    <tr>
        <td>
            ActivityName
        </td>
        <td>The Activity Name in which the Client is enrolled </td>
    </tr>
    <tr>
        <td>AttendanceCount</td>
        <td>A count of the number of attendances for this Client for this ActivityName. This field is only populated if the Attendance marking either tally-counting or normal present/absent marking is </td>
    </tr>
    <tr>
        <td>AttendedTime</td>
        <td>The duration, in seconds, of any attendance for this Client for the ActivityName. This field is only populated if the Attendance marking is in Hours and Minutes</td>
    </tr>
    <tr>
        <td>FunderCode</td>
        <td>The Funder Code assigned to the Activity to which this attendance relates.</td>
    </tr>
    <tr>
        <td>idClient</td>
        <td>The unique system identifier for this client. No other Client information is present in this data set</td>
    </tr>
    <tr>
        <td>ResourceName</td>
        <td>The resource used for / by the ActivityName. Typically this is a room name.</td>
    </tr>
    <tr>
        <td>SessionDate</td>
        <td>The Calendar date to which this Attendance (for this Client and ActivityName) applies.</td>
    </tr>
    <tr>
        <td>SessionDateHalf</td>
        <td>The half-year (service registration year, not calendar year) in which the client attended. Example '2015H2'</td>
    </tr>
    <tr>
        <td>SessionDateQtr</td>
        <td>The quarter-year (service registration year, not calendar year) in which the client attended. Example '2015Q2'</td>
    </tr>
    <tr>
        <td>SessionDateYear</td>
        <td>The year (service registration year, not calendar year) in which the client attended. Example '2015'</td>
    </tr>
    <tr>
        <td>SessionDateYearMonth</td>
        <td>The year and month (service registration year, not calendar year) in which the client attended. Example '2015-05May'</td>
    </tr>
    <tr>
        <td>SessionTime</td>
        <td>The time of day (24-hour clock) at which the session started to which the client attended.</td>
    </tr>
    <tr>
        <td>SignInTime</td>
        <td>The time of day (24-hour clock) when the client signed-in to the Session. This can be different to the <em>SessionTime</em> if the attendance type permits the recording of Hours &Aacute; minutes of attendance. Will be '00:00:00' otherwise.</td>
    </tr>
    <tr>
        <td>SignOutTime</td>
        <td>The time of day (24-hour clock) when the client signed-out of the Session. This can be different to the <em>SessionTime</em> if the attendance type permits the recording of Hours &Aacute; minutes of attendance. Will be '00:00:00' otherwise.</td>
    </tr>
    </table>

CommunityCounts/Views/AnalIntro/vClient.cshtml
@{
    ViewBag.Title = "Analysis - vClient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Analysis - The Data Dictionary for vClient</h2>
<p>
    @Html.ActionLink("Back to Data Dictionary", "DDIntro", "AnalIntro", null, htmlAttributes: new { @class = "btn btn-primary btn-xs" })
</p>
<div class="alert alert-dismissible alert-warning">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Important!</h4>
    <p>There is one vClient record for every client registered in the system</p>
</div>
<table class="table table-bordered table-hover">
    <tr>
        <th>Data Dictionary item</th>
        <th>Brief description</th>
    </tr>
    <tr>
        <td>AgeRange</td>
        <td>The Age bandings as shown on the Client registration form. Examples include '17-25'</td>
    </tr>
    <tr>
        <td>ArmedServicesCurrently</td>
        <td>'0' means that the client is not currently a member of the Armed Services,  '1' means that the client is currently a member of the armed services</td>
    </tr>
    <tr>
        <td>ArmedServicesPreviously</td>
        <td>'0' means that the client was not previously a member of the Armed Services,  '1' means that the client was previously a member of the armed services</td>
    </tr>
    <tr>
        <td>AttainmentTracked</td>
        <td>'0' means that this Client is not tracked for Attainment purposes, '1' means that the client is tracked for Attainment purposes</td>
    </tr>
    <tr>
        <td>Benefits</td>
        <td>The same values as on the Client registration form:<ul><li>'Yes'</li><li>'No'</li><li>'Prefer not to Say'</li></ul></td>
    </tr>
    <tr>
        <td>ClientCreatedDate</td>
        <td>The calendar date that the client was entered into the system</td>
    </tr>
    <tr>
    <td>ClientCreatedHalf</td>
    <td>The half-year (service registration year, not calendar year) in which the client was first entered into the system. Example '2015H2'</td></tr>
    <tr>
        <td>ClientCreatedQtr</td>
        <td>The quarter-year (service registration year, not calendar year) in which the client was first entered into the system. Example '2015Q3'</td>
    </tr>
    <tr>
        <td>ClientCreatedYear</td>
        <td>The service registration year (not calendar year) in which the client was first entered into the system. Example '2015'</td>
    </tr>
    <tr>
        <td>ClientCreatedYearMonth</td>
        <td>The year and month (service registration year, not calendar year) in which the client was first entered into the system. Example '2015-04Apr'</td>
    </tr>
    <tr>
        <td>ClientID</td>
        <td>The unique system identifier for this client</td>
    </tr>
    <tr>
        <td>ClientIDPrev</td>
        <td>The <strong>ClientID</strong> value for this <strong>same</strong> client in a previous year.
        <br />Normally this is in the <strong>previous</strong> registration year but may not be necessarily so. This is because <em>ClientIDPrev</em> is set when a client <strong>from any year</strong> is copied forward to another
        year Hence, <em>ClientIDPrev</em> may refer to any number of years ago but is definately this same client in a previous year to the current year. 
        <p>
            You can use this value to determine if a client is a 'repeat' client or not in that it will have the value of 'blank' if this is a new registration in the current year and will not be blank (will contain a number) if this client
            was previously registered.
        </p>
        </td>
    </tr>
    <tr>
        <td>Disability</td>
        <td>The same values as on the Client registration form:<ul><li>'Yes'</li><li>'No'</li><li>'Prefer not to Say'</li></ul></td>
    </tr>
    <tr>
        <td>District</td>
        <td>The geographical - from Postcode data - <strong>District</strong> in which the client resides</td>
    </tr>
    <tr>
        <td>Ethnicity</td>
        <td>The same values as on the Client registration form. Example 'Mixed Heritage'</td>
    </tr>
    <tr>
        <td>EthnicityOther</td>
        <td>The same value as on the Client registration form if one was entered. Can be any value</td>
    </tr>
    <tr>
        <td>Gender</td>
        <td>The same values as on the Client registration form:<ul><li>'Yes'</li><li>'No'</li><li>'Prefer not to Say'</li></ul></td>
    </tr>
    <tr>
        <td>HearOfServices</td>
        <td>How the Client heard of the Activiy for which they are registering. The same values as on the Client registration form. Example 'Live Locally'</td>
    </tr>
    <tr>
        <td>HearOfServicesOther</td>
        <td>How the Client heard of the Activiy for which they are registering that is not one of the drop-down list values (if one was entered) Can be any value</td>
    </tr>
    <tr>
        <td>HousingStatus</td>
        <td>For the registered address of this Client, value to determine their ownership status of that property.  Examples include:<ul><li>'Owner Occupier'</li></ul></td>
    </tr>
    <tr>
        <td>MemoryStickIssuedDate</td>
        <td>The date that a personal storage device was issued to this Client</td>
    </tr>
    <tr>
        <td>Occupation</td>
        <td>Occupation types as defined on the Client registration form. Examples 'Volunteer' or 'Employed Part time (under 16 hours)'</td>
    </tr>
    <tr>
        <td>OccupationOther</td>
        <td>Occupation types that is not one of the values in the drop-down list (if one was entered). Can be any value</td>
    </tr>
    <tr>
        <td>PostCode</td>
        <td>The registered postcode of the address in which the Client lives</td>
    </tr>
    <tr>
        <td>PreferredLanguage</td>
        <td>The first language of the Client. Example 'Chinese (all dialects)'</td>
    </tr>
    <tr>
        <td>PreferredLanguageOther</td>
        <td>The first language of the Client that is not one of the drop-down list values. Can be any value</td>
    </tr>
    <tr>
        <td>RegistrationYear</td>
        <td>The <strong>service year</strong> for which this client is registered. This is not (necessarily) the same as the calendar year if, for example, a service year starts on 1st April. In this case 1st April 2015 has the same registration year as 1st February 2016 (and would be '2015')</td>
    </tr>
    <tr>
        <td>TenantStatus</td>
        <td>If the <em>HousingStatus</em> field is that of 'Rented Accommodation', further information (as on the registration form) to indicate who their Landlord is. Example 'Waterloo'</td>
    </tr>
    <tr>
        <td>TravelMethod</td>
        <td>How the Client travelled to the Centre when registering. Example 'Car or Motorbike'</td>
    </tr>
    <tr>
        <td>Ward</td>
        <td>The geographical - from Postcode data - <strong>Ward</strong> in which the client resides</td>
    </tr>

</table>

CommunityCounts/Views/AnalIntro/vClientActivity.cshtml
@{
    ViewBag.Title = "Analysis - vClientActivity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Analysis - The Data Dictionary for vClientActivity</h2>
<p>
    @Html.ActionLink("Back to Data Dictionary", "DDIntro", "AnalIntro", null, htmlAttributes: new { @class = "btn btn-primary btn-xs" })
</p>
<div class="alert alert-dismissible alert-warning">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Important!</h4>
    <p>There is one vClientActivity record for each client enrollment in every Activity. As a Client may enrol in more than 1 Activity, there are multiple records for each Client.</p>
</div>
<table class="table table-bordered table-hover">
    <tr>
        <th>Data Dictionary item</th>
        <th>Brief description</th>
    </tr>
    <tr>
        <td>
            ActivityName
        </td>
        <td>The Activity Name in which the Client is enrolled </td>
    </tr>
    <tr>
        <td>AgeRange</td>
        <td>The Age bandings as shown on the Client registration form. Examples include '17-25'</td>
    </tr>
    <tr>
        <td>ArmedServicesCurrently</td>
        <td>'0' means that the client is not currently a member of the Armed Services,  '1' means that the client is currently a member of the armed services</td>
    </tr>
    <tr>
        <td>ArmedServicesPreviously</td>
        <td>'0' means that the client was not previously a member of the Armed Services,  '1' means that the client was previously a member of the armed services</td>
    </tr>
    <tr>
        <td>AttainmentTracked</td>
        <td>'0' means that this Client is not tracked for Attainment purposes, '1' means that the client is tracked for Attainment purposes</td>
    </tr>
    <tr>
        <td>Benefits</td>
        <td>The same values as on the Client registration form:<ul><li>'Yes'</li><li>'No'</li><li>'Prefer not to Say'</li></ul></td>
    </tr>
    <tr>
        <td>ClientCreatedDate</td>
        <td>The calendar date that the client was entered into the system</td>
    </tr>
    <tr>
        <td>ClientCreatedHalf</td>
        <td>The half-year (service registration year, not calendar year) in which the client was first entered into the system. Example '2015H2'</td>
    </tr>
    <tr>
        <td>ClientCreatedQtr</td>
        <td>The quarter-year (service registration year, not calendar year) in which the client was first entered into the system. Example '2015Q3'</td>
    </tr>
    <tr>
        <td>ClientCreatedYear</td>
        <td>The service registration year (not calendar year) in which the client was first entered into the system. Example '2015'</td>
    </tr>
    <tr>
        <td>ClientCreatedYearMonth</td>
        <td>The year and month (service registration year, not calendar year) in which the client was first entered into the system. Example '2015-04Apr'</td>
    </tr>
    <tr>
        <td>ClientID</td>
        <td>The unique system identifier for this client</td>
    </tr>
    <tr>
        <td>ClientIDPrev</td>
        <td>
            The <strong>ClientID</strong> value for this <strong>same</strong> client in a previous year.
            <br />Normally this is in the <strong>previous</strong> registration year but may not be necessarily so. This is because <em>ClientIDPrev</em> is set when a client <strong>from any year</strong> is copied forward to another
            year Hence, <em>ClientIDPrev</em> may refer to any number of years ago but is definately this same client in a previous year to the current year.
            <p>
                You can use this value to determine if a client is a 'repeat' client or not in that it will have the value of 'blank' if this is a new registration in the current year and will not be blank (will contain a number) if this client
                was previously registered.
            </p>
        </td>
    </tr>
    <tr>
        <td>Disability</td>
        <td>The same values as on the Client registration form:<ul><li>'Yes'</li><li>'No'</li><li>'Prefer not to Say'</li></ul></td>
    </tr>
    <tr>
        <td>District</td>
        <td>The geographical - from Postcode data - <strong>District</strong> in which the client resides</td>
    </tr>
    <tr>
        <td>EnrolledDate</td>
        <td>The calendar date that the client enrolled in the Activity</td>
    </tr>
    <tr>
        <td>EnrolledHalf</td>
        <td>The half-year (service registration year, not calendar year) in which the client was enrolled into this Activity. Example '2015H2'</td>
    </tr>
    <tr>
        <td>EnrolledQtr</td>
        <td>The quarter-year (service registration year, not calendar year) in which the client was enrolled into this Activity. Example '2015Q2'</td>
    </tr>
    <tr>
        <td>EnrolledYear</td>
        <td>The year (service registration year, not calendar year) in which the client was enrolled into this Activity. Example '2015'</td>
    </tr>
    <tr>
        <td>EnrolledYearMonth</td>
        <td>The year and month (service registration year, not calendar year) in which the client was enrolled into this Activity. Example '2015-05May'</td>
    </tr>
    <tr>
        <td>Ethnicity</td>
        <td>The same values as on the Client registration form. Example 'Mixed Heritage'</td>
    </tr>
    <tr>
        <td>EthnicityOther</td>
        <td>The same value as on the Client registration form if one was entered. Can be any value</td>
    </tr>
    <tr>
        <td>Gender</td>
        <td>The same values as on the Client registration form:<ul><li>'Yes'</li><li>'No'</li><li>'Prefer not to Say'</li></ul></td>
    </tr>
    <tr>
        <td>HasJourneys?</td>
        <td>'0' means that this Activity has not been Journeyed onto another Activity. '1' means that this Activity has been journeyed onto another Activity. The linking between such Activities can be explored with the vJourneys data set.</td>
    </tr>
    <tr>
        <td>HearOfServices</td>
        <td>How the Client heard of the Activiy for which they are registering. The same values as on the Client registration form. Example 'Live Locally'</td>
    </tr>
    <tr>
        <td>HearOfServicesOther</td>
        <td>How the Client heard of the Activiy for which they are registering that is not one of the drop-down list values (if one was entered) Can be any value</td>
    </tr>
    <tr>
        <td>HousingStatus</td>
        <td>For the registered address of this Client, value to determine their ownership status of that property.  Examples include:<ul><li>'Owner Occupier'</li></ul></td>
    </tr>
    <tr>
        <td>idServiceType</td>
        <td>A system identified - like ClientID - that uniquely identifies the Activity Type</td>
    </tr>
    <tr>
        <td>JourneyCatDesc</td>
        <td>Optional Field. If set, it contains the Journey Category Description (long name). Such Categories are assigned when the Client progresses from this Activity to a service outside that of the organisation that originally provided this Activity</td>
    </tr>
    <tr>
        <td>JourneycatName</td>
        <td>Optional Field. If set, it contains the Journey Category Name (Short name). Such Categories are assigned when the Client progresses from this Activity to a service outside that of the organisation that originally provided this Activity</td>
    </tr>
    <tr>
        <td>MemoryStickIssuedDate</td>
        <td>The date that a personal storage device was issued to this Client</td>
    </tr>
    <tr>
        <td>Occupation</td>
        <td>Occupation types as defined on the Client registration form. Examples 'Volunteer' or 'Employed Part time (under 16 hours)'</td>
    </tr>
    <tr>
        <td>OccupationOther</td>
        <td>Occupation types that is not one of the values in the drop-down list (if one was entered). Can be any value</td>
    </tr>
    <tr>
        <td>PostCode</td>
        <td>The registered postcode of the address in which the Client lives</td>
    </tr>
    <tr>
        <td>PreferredLanguage</td>
        <td>The first language of the Client. Example 'Chinese (all dialects)'</td>
    </tr>
    <tr>
        <td>PreferredLanguageOther</td>
        <td>The first language of the Client that is not one of the drop-down list values. Can be any value</td>
    </tr>
    <tr>
        <td>RegistrationYear</td>
        <td>The <strong>service year</strong> for which this client is registered. This is not (necessarily) the same as the calendar year if, for example, a service year starts on 1st April. In this case 1st April 2015 has the same registration year as 1st February 2016 (and would be '2015')</td>
    </tr>
    <tr>
        <td>TenantStatus</td>
        <td>If the <em>HousingStatus</em> field is that of 'Rented Accommodation', further information (as on the registration form) to indicate who their Landlord is. Example 'Waterloo'</td>
    </tr>
    <tr>
        <td>TravelMethod</td>
        <td>How the Client travelled to the Centre when registering. Example 'Car or Motorbike'</td>
    </tr>
    <tr>
        <td>UnenrolledDate</td>
        <td>The Calendar date when the client was unenrolled from this Activity. May not be present (as it is an optional field)</td>
    </tr>
    <tr>
        <td>Ward</td>
        <td>The geographical - from Postcode data - <strong>Ward</strong> in which the client resides</td>
    </tr>
</table>

CommunityCounts/Views/AnalIntro/vQCSR.cshtml
@{
    ViewBag.Title = "Analysis - vQCSR";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Analysis - The Data Dictionary for vQCSR</h2>
<p>
    @Html.ActionLink("Back to Data Dictionary", "DDIntro", "AnalIntro", null, htmlAttributes: new { @class = "btn btn-primary btn-xs" })
</p>
<div class="alert alert-dismissible alert-warning">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Important!</h4>
    <p>There is one vQCSR record for each signpost or referral performed. This records Quick Comments, Signposts and Referrals.</p>
</div>
<table class="table table-bordered table-hover">
    <tr>
        <th>Data Dictionary item</th>
        <th>Brief description</th>
    </tr>
    <tr>
        <td>QCSRCategory</td>
        <td>The category (from <em>Setup : S/R Categories</em>)</td>
    </tr>
    <tr>
        <td>QCSRCreateDateTime</td>
        <td>The date and time that this QCSR record was entered into the system</td>
    </tr>
    <tr>
        <td>QCSRCreatedDateHalf</td>
        <td>The half-year (service registration year, not calendar year) in which this record was first entered into the system. Example '2015H2'</td>
    </tr>
    <tr>
        <td>QCSRCreatedDateQtr</td>
        <td>The quarter-year (service registration year, not calendar year) in which this record was first entered into the system. Example '2015Q3'</td>
    </tr>
    <tr>
        <td>QCSRCreatedDateYear</td>
        <td>The service registration year (not calendar year) in which thiks record was first entered into the system. Example '2015'</td></td>
    </tr>
    <tr>
        <td>QCSRCreatedDateYearMonth</td>
        <td>The year and month (service registration year, not calendar year) in which this record was first entered into the system. Example '2015-04Apr'</td></td>
    </tr>
    <tr>
        <td>RegistrationYear</td>
        <td>The <strong>service year</strong> for which this client is registered. This is not (necessarily) the same as the calendar year if, for example, a service year starts on 1st April. In this case 1st April 2015 has the same registration year as 1st February 2016 (and would be '2015')</td>
    </tr>
    <tr>
        <td>RegYearEndDate</td>
        <td>The last date in the <strong>RegistrationYear</strong></td>
    </tr>
    <tr>
        <td>RegYearStartDate</td>
        <td>The first date in the <strong>RegistrationYear</strong></td>
    </tr>
    <tr>
        <td>Signpost?</td>
        <td>
            '0' means that this record is not a Signpost and so is a <strong>Referral</strong>. '1' means that this record is a Signpost 
        </td>
    </tr>
    <tr>
        <td>SRComment</td>
        <td>Free-form text - the comment entered into the online system</td>
    </tr>
    </table>