CommunityCounts/Models/Master/C1service.cs
namespace CommunityCounts.Models.Master
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ccmaster.1service")]
    public partial class C1service
    {
        public C1service()
        {
            C1journeys = new HashSet<C1journeys>();
        }

        [Key]
        public int idService { get; set; }

        public int idClient { get; set; }

        public int idServiceType { get; set; }

        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Created Date")]
        public DateTime CreateDate { get; set; }

        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Unenrolled date")]
        public DateTime? EndedDate { get; set; }

        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Enrolled date")]
        public DateTime StartedDate { get; set; }

        public int JourneyedidCategory { get; set; }

        public bool JourneyedServices { get; set; }

        public virtual C1client C1client { get; set; }

        public virtual C1journeycat C1journeycat { get; set; }

        public virtual ICollection<C1journeys> C1journeys { get; set; }

        public virtual C1servicetypes C1servicetypes { get; set; }
    }
}

CommunityCounts/Models/Master/C1servicetypes.cs
namespace CommunityCounts.Models.Master
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ccmaster.1servicetypes")]
    public partial class C1servicetypes
    {
        public C1servicetypes()
        {
            C1attendance = new HashSet<C1attendance>();
            C1bookings = new HashSet<C1bookings>();
            C1schedules = new HashSet<C1schedules>();
            C1service = new HashSet<C1service>();
            C1surveys = new HashSet<C1surveys>();
            C1clientcaseservice = new HashSet<C1clientcaseservice>();
        }

        [Key]
        public int idServiceType { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Activity Name")]
        public string ServiceType { get; set; }

        [Display(Name = "Attendance recording type")]
        public int AttendanceType { get; set; }

        [Required]
        [StringLength(15)]
        [Display(Name = "Funder")]
        public string FunderCode { get; set; }

        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Ended Date")]
        public DateTime? EndedDate { get; set; }

        public virtual ICollection<C1attendance> C1attendance { get; set; }

        public virtual ICollection<C1bookings> C1bookings { get; set; }

        public virtual C1funders C1funders { get; set; }

        public virtual ICollection<C1schedules> C1schedules { get; set; }

        public virtual ICollection<C1service> C1service { get; set; }

        public virtual ICollection<C1surveys> C1surveys { get; set; }

        public virtual refdata refdata { get; set; }
        public virtual ICollection<C1clientcaseservice> C1clientcaseservice { get; set; }
    }
}

CommunityCounts/Controllers/Master/ClientCaseWorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using CommunityCounts.Models.Master;
using CommunityCounts.Global_Methods;



namespace CommunityCounts.Controllers
{
    [Authorize(Roles = "superAdmin,systemAdmin,canManageCase")]
    public class ClientCaseWorkController : Controller
    {
        private ccMaster db = new ccMaster(null); // open the database
        // GET: ClientCaseWork
        public ActionResult CaseWorkSummary(int? id)  // id passed is idClient
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var getClientName = from c in db.C1client where (c.idClient == id) select new { c.FirstName, c.LastName, c.scramble };
            ViewBag.FirstName = CS.unscramble(getClientName.First().FirstName, getClientName.First().scramble);
            ViewBag.LastName = CS.unscramble(getClientName.First().LastName, getClientName.First().scramble);
            ViewBag.idClient = id;
            var ClientCaseHeader = db.C1clientcaseheader.Where(a => a.idClient == id); // Get any? exisiting casework records for this idClient
            //
            List<clientCaseWorkList> caseList = new List<clientCaseWorkList>();
            TimeSpan totalTime = new TimeSpan(0, 0, 0); // hours minutes seconds integers
            string serviceName,staffName;
            char[] splitChar;
            //
            if (ClientCaseHeader.Any())
            {

                ViewBag.startCaseWorking = false;
                var idClientCaseHeader = ClientCaseHeader.First().idClientCaseHeader;
                ViewBag.idClientCaseHeader = idClientCaseHeader;
                var caseService = db.C1clientcaseservice.Where(a => a.idClientCaseHeader==idClientCaseHeader);
                foreach (var serviceRec in caseService.ToList())
                {
                    int idClientCaseDetail = serviceRec.idClientCaseDetail; // grab the key of all children for this Service
                    //
                    // Loop over all detail recs to add up time - cannot do this by aggregate function
                    //
                    var caseservicedetails = db.C1clientcaseservicedetail.Where(a => a.idClientCaseDetail == idClientCaseDetail).OrderByDescending(a => a.CaseServiceDate);
                    long totalTimeToDate = 0;
                    int? lastStaff = 0;
                    int numDetailRecs = 0;
                    foreach (var details in caseservicedetails)
                    {
                        totalTimeToDate = totalTimeToDate + details.CaseServiceTime.Ticks;
                        lastStaff = details.CaseServiceStaffid;
                        numDetailRecs++;
                    }
                    if (lastStaff!=0)
                    {
                        staffName = db.users.Find(lastStaff).Email;
                        splitChar = "@".ToCharArray();
                        var logonParts = staffName.Split(splitChar[0]); // Email domain will be in 2nd part (index=1)
                        staffName = logonParts[0]; // gets username from email address
                    }
                    else
                    {
                        staffName = null;
                    }
                    totalTime = new TimeSpan(new DateTime(totalTimeToDate).Hour, new DateTime(totalTimeToDate).Minute, new DateTime(totalTimeToDate).Second);
                    serviceName = db.C1servicetypes.Find(serviceRec.ServiceTypesid).ServiceType; // service name
                    //
                    TimeSpan t = new TimeSpan(totalTimeToDate); // convert ticks to timespan
                    int totalSeconds = t.Seconds;
                    int totalMinutes = t.Minutes;
                    int totalDays = t.Days;
                    int totalHours = t.Hours + totalDays * 24;
                    string formattedTime = totalHours.ToString("#,###") + ":" + totalMinutes.ToString("00");
                    caseList.Add(new clientCaseWorkList
                    {
                        numDetailRecs = numDetailRecs,
                        staffName = staffName,
                        totalTimeToDate = totalTime,
                        totalTimeToDateFormatted = formattedTime,
                        ServiceName = serviceName,
                        isCaseWorked = false,
                        idClientCaseDetail = serviceRec.idClientCaseDetail
                    });
                }
            }
            else
            {
                ViewBag.startCaseWorking = true;
            }
            var sortedList = caseList.OrderBy(a => a.ServiceName);
            return View(caseList);
        }
        //Get ClientCaseWork/CreateCaseService/id
        public ActionResult CreateCaseService (int idClientCaseHeader)
        {
            List<clientCaseWorkSelList> selList = new List<clientCaseWorkSelList>();
            //
            // Build Activity selection list from any previous casework records AND any new activity enrollments (since casework started)
            //
            int idClient = db.C1clientcaseheader.Find(idClientCaseHeader).idClient;
            var getClientName = from c in db.C1client where (c.idClient == idClient) select new { c.FirstName, c.LastName, c.scramble };
            ViewBag.FirstName = CS.unscramble(getClientName.First().FirstName, getClientName.First().scramble);
            ViewBag.LastName = CS.unscramble(getClientName.First().LastName, getClientName.First().scramble);
            ViewBag.idClient = idClient;
            var existingActivities = from a in db.C1service where (a.idClient == idClient & ((a.EndedDate == null) || (a.EndedDate > System.DateTime.Now))) select new { a.idServiceType, a.StartedDate };
            //
            foreach (var activityRec in existingActivities.ToList())
            {
                string serviceName = db.C1servicetypes.Find(activityRec.idServiceType).ServiceType;
                bool isCaseWorked = db.C1clientcaseservice.Where(a => a.ServiceTypesid == activityRec.idServiceType).Any();
                selList.Add(new clientCaseWorkSelList
                {
                    idClientCaseHeader = idClientCaseHeader,
                    idServiceType = activityRec.idServiceType,
                    startedDate = activityRec.StartedDate,
                    ServiceName = serviceName,
                    isCaseWorked = isCaseWorked
                });
            }
            return View(selList);
        }
        // POST: ClientCaseWork/CreateCaseService/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCaseService([Bind(Include = "isCaseWorked,idServiceType,idClientCaseHeader")] List<clientCaseWorkSelList> selList)
        {
            //
            if (selList.Where(a=>a.isCaseWorked==true).Count() == 0)
            {
                ModelState.AddModelError("", "Please tick at least one Activity to be Caseworked or press 'Back to List' to cancel");
            }
            //
            // check that records previous marked for Caseworking are now not-unselected (cannot use readonly attr on <input> to stop this)
            //
            foreach (var i in selList)
            {
                var rec = db.C1clientcaseservice.Where(a => a.idClientCaseHeader == i.idClientCaseHeader).Where(a => a.ServiceTypesid == i.idServiceType);
                if (rec.Any())
                {
                    if (!i.isCaseWorked)
                    {
                        ModelState.AddModelError("", "You cannot untick already marked records as Casework details exist. Use the Delete action on the Client Casework Summary Screen to remove all CaseWorking activity for this client/Activity after pressing the 'Back to List' option.");
                    }
                }
            }
            int idClient = db.C1clientcaseheader.Find(selList[0].idClientCaseHeader).idClient;
            if (ModelState.IsValid)
            {   
                foreach (var i in selList)
                {
                    //
                    // Does this casework detail record already exist? If not,add it.
                    //
                    if (!db.C1clientcaseservice.Where(a => a.idClientCaseHeader == i.idClientCaseHeader).Where(a => a.ServiceTypesid == i.idServiceType).Any())
                    {
                        if (i.isCaseWorked)
                        {
                            db.C1clientcaseservice.Add(new C1clientcaseservice
                            {
                                idClientCaseHeader = i.idClientCaseHeader,
                                ServiceTypesid = i.idServiceType,
                                isCaseWorked = i.isCaseWorked
                            });
                        }
                    }

                }
                db.SaveChanges();
                return RedirectToAction("CaseWorkSummary", new { id = idClient });
            }
            var getClientName = from c in db.C1client where (c.idClient == idClient) select new { c.FirstName, c.LastName, c.scramble };
            ViewBag.FirstName = CS.unscramble(getClientName.First().FirstName, getClientName.First().scramble);
            ViewBag.LastName = CS.unscramble(getClientName.First().LastName, getClientName.First().scramble);
            ViewBag.idClient = idClient;
            foreach (var i in selList)
            {
                i.ServiceName= db.C1servicetypes.Find(i.idServiceType).ServiceType;
            }
            return View(selList);
        }
        public ActionResult StartCaseService(int idClient)
        {
            //
            // set up caseworking tables for idClient
            //
          
            if (db.C1clientcaseheader.Where(a=>a.idClient==idClient).Any())
            {

CommunityCounts/Views/C1service/ClientCaseWork/CaseWorkSummary.cshtml
@model List<CommunityCounts.Models.Master.clientCaseWorkList>

@{
    ViewBag.Title = "Client Case Work";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Client Case Work Summary</h2>
<h3>Client Name: @ViewBag.FirstName @ViewBag.LastName</h3>
<p>
    @Html.ActionLink("Back to List", "Index","C1client", new { SearchStringName = @ViewBag.idClient }, htmlAttributes: new { @class = "btn btn-primary btn-xs" })
    @if(ViewBag.startCaseWorking)
    {
        @Html.ActionLink("Start Caseworking", "StartCaseService", new { idClient = @ViewBag.idClient }, htmlAttributes: new { @class = "btn btn-warning btn-xs" })
    }
    else
    {
        @Html.ActionLink("OverView","OverView",new {id = @ViewBag.idClient},htmlAttributes: new { @class = "btn btn-primary btn-xs"})
        
        @Html.ActionLink("Casework another Activity", "CreateCaseService", new { idClientCaseHeader = @ViewBag.idClientCaseHeader }, htmlAttributes: new { @class = "btn btn-warning btn-xs" })  
    }
</p>
<table class="table table-hover" >
    <tr>
        <th>
            Activity
        </th>
        <th>
            Last Staff
        </th>
        <th width="100px" >
            Number of Caseworking events
        </th>
        <th width="100px" align="right">
            Total Staff Time
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ServiceName)
        </td>
        <td>
            @Html.DisplayFor(modelitem => item.staffName)
        </td>
        <td align="right">
            @Html.DisplayFor(modelItem => item.numDetailRecs)
        </td>
        <td align="right">
            @Html.DisplayFor(modelItem=> item.totalTimeToDateFormatted)
        </td>
        <td>
            @Html.ActionLink("Details", "Index","ClientCaseWorkDetail", new { id = item.idClientCaseDetail }, htmlAttributes: new { @class = "btn btn-primary  btn-xs" }) 
            @Html.ActionLink("Delete", "DeleteCaseWork", new { id = item.idClientCaseDetail }, htmlAttributes: new { @class = "btn btn-danger btn-xs" })
        </td>
    </tr>
}

</table>

CommunityCounts/Views/C1service/ClientCaseWork/CreateCaseService.cshtml
@model List<CommunityCounts.Models.Master.clientCaseWorkSelList>
@{
    ViewBag.Title = "Casework selection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Select which activities are to be Caseworked for a Client</h2>
<h3>Client Name: @ViewBag.FirstName @ViewBag.LastName</h3>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ActionLink("Back to List", "CaseWorkSummary", new {id=ViewBag.idClient}, htmlAttributes: new { @class = "btn btn-primary btn-xs" })
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @{int counter = 0;}
        <table class="table-condensed">
            <tr>
               
                <th align="right" width="60px">
                    Case Worked
                </th>
                <th align="left">
                    Enrolled Activity
                </th>
            </tr>
            @foreach (var item in Model)
        {
                <tr>
                    <td align="right" width="100px">
                        @if (item.isCaseWorked)
                    {
                            <input name="[@counter].isCaseWorked" type="checkbox" checked id="[@counter].isCaseWorked" value="true"  /> @* return this if user clicked *@

                    }
                    else
                    {
                            <input name="[@counter].isCaseWorked" type="checkbox" id="[@counter].isCaseWorked" value="true"  />
                    }
                        <input type="hidden" value="false" name="[@counter].isCaseWorked" />                                      @* Otherwise this *@

                    </td>
                    <td align="Left">
                        <input name="[@counter].idServiceType" type="hidden" value="@item.idServiceType" />     @* Stack keys hidden to get them back in HTTPPOST*@
                        <input name="[@counter].idClientCaseHeader" type="hidden" value="@item.idClientCaseHeader" /> 
                        @Html.DisplayFor(modelitem => item.ServiceName)
                    </td>
                </tr>
                    counter++;
        }
            </table>

        <div class="form-group">
            <div class="col-md-offset-1 col-md-4">
                <input type="submit" value="Save" class="btn btn-warning btn-xs" />
            </div>
        </div>
</div>
}
<div class="alert alert-dismissible alert-warning">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <h4>Please Note</h4>
    <p>You need to <a href="/C1service/Index/@ViewBag.idClient" class="alert-link">Enrol</a> this Client in more Activities, if they are not listed here, if you need to casework another Activity for this Client .</p>
</div>

CommunityCounts/Views/C1service/ClientCaseWork/DeletecaseWork.cshtml
@{
    ViewBag.Title = "Delete CaseWork";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete all Casework events for a Client and Activity</h2>
@{string route ="CaseWorkSummary/" + ViewBag.idClient;} 
@Html.ActionLink("No - Back to List", route, null, htmlAttributes: new { @class = "btn btn-primary btn-xs" })
<div class="alert alert-dismissable alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>Warning!</strong> Are you sure that you want to delete ALL casework for Client @ViewBag.FirstName @ViewBag.LastName against activity @ViewBag.ActivityName?
</div>
<div>
  
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
<div class="alert alert-dismissable alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>Important!</strong> Pressing the Delete button below will delete all casework records for activity @ViewBag.ActivityName!
</div>
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-xs" />
        </div>
    }
    </div>

CommunityCounts/Views/C1service/ClientCaseWork/OverView.cshtml
@model List<CommunityCounts.Models.Master.clientCaseWorkOverView>

@{
    ViewBag.Title = "OverView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All CaseWork events for a Client</h2>
<h3>Client Name   : @ViewBag.FirstName @ViewBag.LastName</h3>

<p>
    @Html.ActionLink("Back to List", "CaseWorkSummary","ClientCaseWork", new {id=@ViewBag.idClient}, htmlAttributes: new { @class = "btn btn-primary btn-xs" })
   
<table class="table">
    <tr>
        
        <th width="10%">
            CaseWork StartDate
        </th>
        
        <th width="10%">
           Last Edit Date/Time
        </th>
        <th>
           Activity
        </th>
        <th>
            Name
        </th>
        <th>
           Hours
        </th>
        
        <th width="45%">
            Notes
        </th>
   
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.CaseServiceDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CaseServiceEditDate)
        </td>
        <td>
            @Html.DisplayFor(x => item.ServiceName)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td align="right">
            @Html.DisplayFor(modelItem => item.CaseServiceTime)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.CaseServiceNotes)
        </td>
        
    </tr>
}

</table>